# Generated by Django 3.0.5 on 2020-06-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
