# Generated by Django 3.0.5 on 2020-06-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Profile_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
