# Generated by Django 3.0.7 on 2020-06-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=120)),
                ('contact_number', models.CharField(max_length=20)),
                ('shop_address', models.CharField(max_length=250)),
                ('comment', models.TextField()),
            ],
        ),
    ]
