# Generated by Django 3.0.5 on 2020-06-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Profile_category',
            field=models.CharField(blank=True, default='User', max_length=100),
        ),
    ]
