# Generated by Django 3.0.7 on 2020-08-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200629_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='phone_number',
            new_name='email',
        ),
    ]
