# Generated by Django 3.0.5 on 2020-06-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200617_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='service',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
