# Generated by Django 3.1.2 on 2020-10-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200818_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=500)),
                ('shop_address', models.CharField(max_length=500)),
            ],
        ),
    ]
