# Generated by Django 3.1.2 on 2020-11-22 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_merchant_shop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('set_id', models.IntegerField(primary_key=True, serialize=False)),
                ('set_topic', models.CharField(max_length=500)),
                ('set_date', models.CharField(max_length=500)),
                ('set_question1', models.CharField(max_length=500)),
                ('set_option1a', models.CharField(max_length=500)),
                ('set_option1b', models.CharField(max_length=500)),
                ('set_option1c', models.CharField(max_length=500)),
                ('set_answer1', models.CharField(max_length=500)),
                ('set_img1', models.CharField(max_length=500)),
                ('set_question2', models.CharField(max_length=500)),
                ('set_option2a', models.CharField(max_length=500)),
                ('set_option2b', models.CharField(max_length=500)),
                ('set_option2c', models.CharField(max_length=500)),
                ('set_answer2', models.CharField(max_length=500)),
                ('set_img2', models.CharField(max_length=500)),
                ('set_question3', models.CharField(max_length=500)),
                ('set_option3a', models.CharField(max_length=500)),
                ('set_option3b', models.CharField(max_length=500)),
                ('set_option3c', models.CharField(max_length=500)),
                ('set_answer3', models.CharField(max_length=500)),
                ('set_img3', models.CharField(max_length=500)),
                ('set_question4', models.CharField(max_length=500)),
                ('set_option4a', models.CharField(max_length=500)),
                ('set_option4b', models.CharField(max_length=500)),
                ('set_option4c', models.CharField(max_length=500)),
                ('set_answer4', models.CharField(max_length=500)),
                ('set_img4', models.CharField(max_length=500)),
                ('set_question5', models.CharField(max_length=500)),
                ('set_option5a', models.CharField(max_length=500)),
                ('set_option5b', models.CharField(max_length=500)),
                ('set_option5c', models.CharField(max_length=500)),
                ('set_answer5', models.CharField(max_length=500)),
                ('set_img5', models.CharField(max_length=500)),
                ('set_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
        ),
    ]
