# Generated by Django 3.0.5 on 2020-06-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oder_id', models.IntegerField(primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(blank=True, max_length=100)),
                ('merchant_name', models.CharField(blank=True, max_length=100)),
                ('order_total', models.CharField(blank=True, max_length=100)),
                ('order_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
