# Generated by Django 3.0.5 on 2020-06-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_availability',
            field=models.BooleanField(default=True),
        ),
    ]
