# Generated by Django 3.0.7 on 2020-08-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trending_title', models.CharField(max_length=500, null=True)),
                ('trending_logo', models.CharField(max_length=500, null=True)),
                ('trending_date', models.CharField(max_length=500, null=True)),
                ('trending_url', models.IntegerField()),
            ],
        ),
    ]
